# Generated by Django 5.1.1 on 2025-06-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0001_initial'),
        ('languages_plus', '0004_auto_20171214_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='speakers', to='languages_plus.language'),
        ),
    ]
