# Generated by Django 5.1.1 on 2025-06-04 14:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0002_gig_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='price',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='images/profile_pics/default_profile.jpg', upload_to='images/profile_pics/'),
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='freelance_app.gig')),
            ],
        ),
        migrations.CreateModel(
            name='PricingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('CUSTOM', 'Custom')], max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('description', models.CharField(max_length=200)),
                ('related_pricingPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='freelance_app.pricingplan')),
            ],
        ),
    ]
