# Generated by Django 5.2.4 on 2026-06-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0003_delivery_deliveryattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryattachment",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryattachment",
            name="file_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
