# Generated by Django 5.1.1 on 2025-06-06 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0003_remove_gig_price_alter_user_profile_pic_pricingplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingoption',
            name='delivery_time',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
