# Generated by Django 5.2.4 on 2026-06-17 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0005_order_delivery_time_order_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingoption",
            name="delivery_time",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pricingoption",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
