# Generated by Django 5.1.1 on 2025-06-06 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0005_alter_pricingplan_related_gig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='related_gig',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plan', to='freelance_app.gig'),
        ),
    ]
