# Generated by Django 5.2.4 on 2026-06-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0006_alter_pricingoption_delivery_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
