# Generated by Django 5.1.1 on 2025-06-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0006_alter_pricingplan_related_gig'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tagline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
