# Generated by Django 5.2.4 on 2026-06-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0007_alter_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricingoption",
            old_name="type",
            new_name="tier",
        ),
    ]
