# Generated by Django 5.2.4 on 2026-06-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "freelance_app",
            "0009_gig_allow_custom_offers_alter_delivery_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In_Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("OVERDUE", "Overdue"),
                ],
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
    ]
