# Generated by Django 5.2.4 on 2026-06-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0010_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reqs_submitted_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
