# Generated by Django 5.2.4 on 2026-06-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0011_order_reqs_submitted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="order",
            old_name="created_on",
            new_name="placed_at",
        ),
    ]
