# Generated by Django 5.2.4 on 2026-06-20 10:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0012_orderactivitylog_rename_created_on_order_placed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='created_at',
            new_name='delivered_at',
        ),
        migrations.AddField(
            model_name='orderactivitylog',
            name='related_order',
            field=models.OneToOneField(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='freelance_app.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricingoption',
            name='delivery_time',
            field=models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricingoption',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pricingoption',
            name='price',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PENDING_RESPONSE', 'Pending Response'), ('QUOTED', 'Quoted')], default='PENDING_RESPONSE', max_length=20)),
                ('requirements', models.TextField(max_length=3000)),
                ('delivery_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to=settings.AUTH_USER_MODEL)),
                ('related_gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='freelance_app.gig')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(max_length=300)),
                ('related_activityLog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_activity', to='freelance_app.orderactivitylog')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PENDING_RESPONSE', 'Pending_Response')], default='PENDING_RESPONSE', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(max_length=1000)),
                ('delivery_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations_received', to=settings.AUTH_USER_MODEL)),
                ('related_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='freelance_app.offer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
