# Generated by Django 5.2.4 on 2026-06-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0013_rename_created_at_delivery_delivered_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="starting_price",
            field=models.DecimalField(decimal_places=2, default=22, max_digits=10),
            preserve_default=False,
        ),
    ]
