# Generated by Django 5.2.4 on 2026-06-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0014_gig_starting_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="joined_date",
        ),
    ]
