# Generated by Django 5.2.4 on 2026-07-01 06:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0015_remove_user_joined_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gig",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gigs",
                to="freelance_app.category",
            ),
        ),
        migrations.AlterField(
            model_name="gig",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/gig_covers/"
            ),
        ),
        migrations.AlterField(
            model_name="gig",
            name="description",
            field=models.TextField(
                max_length=2000,
                validators=[
                    django.core.validators.MinLengthValidator(
                        50, message="Description must be at least 50 characters long."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="gig",
            name="starting_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("1.00"),
                        message="Starting price cannot be less than $1.00.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="gig",
            name="title",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(
                        15, message="Title must be atleast 15 characters long"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="related_pricing_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="freelance_app.pricingoption",
            ),
        ),
        migrations.AlterField(
            model_name="pricingoption",
            name="tier",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic"),
                    ("STANDARD", "Standard"),
                    ("PREMIUM", "Premium"),
                ],
                max_length=10,
            ),
        ),
    ]
