# Generated by Django 5.2.4 on 2026-07-02 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0017_alter_order_buyer_alter_order_related_gig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gigreview",
            name="related_order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="freelance_app.order",
            ),
        ),
        migrations.AlterField(
            model_name="gigreview",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gig_review_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
