# Generated by Django 5.2.4 on 2026-07-02 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0018_gigreview_related_order_alter_gigreview_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gigreview",
            name="related_order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="freelance_app.order",
            ),
        ),
    ]
