# Generated by Django 5.2.4 on 2026-07-02 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0019_alter_gigreview_related_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="related_offer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotations",
                to="freelance_app.offer",
            ),
        ),
    ]
