# Generated by Django 5.2.4 on 2026-07-05 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0020_alter_quotation_related_offer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offer",
            old_name="delivery_time",
            new_name="delivery_days",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="delivery_time",
            new_name="delivery_days",
        ),
        migrations.RenameField(
            model_name="pricingoption",
            old_name="delivery_time",
            new_name="delivery_days",
        ),
        migrations.RenameField(
            model_name="quotation",
            old_name="delivery_time",
            new_name="delivery_days",
        ),
        migrations.AddField(
            model_name="order",
            name="due_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
