# Generated by Django 5.2.4 on 2026-07-05 14:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0021_rename_delivery_time_offer_delivery_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderactivity",
            name="related_activityLog",
        ),
        migrations.AddField(
            model_name="orderactivity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderactivity",
            name="related_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="freelance_app.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderactivity",
            name="details",
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name="OrderActivityLog",
        ),
    ]
