# Generated by Django 5.2.4 on 2026-07-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0022_remove_orderactivity_related_activitylog_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricingoption",
            name="related_pricingPlan",
        ),
        migrations.RenameField(
            model_name="gig",
            old_name="cover_image",
            new_name="thumbnail",
        ),
        migrations.AddField(
            model_name="pricingoption",
            name="related_gig",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_options",
                to="freelance_app.gig",
            ),
        ),
        migrations.DeleteModel(
            name="PricingPlan",
        ),
    ]
