# Generated by Django 5.2.4 on 2026-07-12 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0024_alter_gigreview_rating_alter_sellerreview_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="due_at",
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name="RevisionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requirements", models.TextField(max_length="2000")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_request",
                        to="freelance_app.delivery",
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="freelance_app.order",
                    ),
                ),
            ],
        ),
    ]
