# Generated by Django 5.2.4 on 2026-07-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0025_alter_order_due_at_revisionrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revisionrequest",
            name="requirements",
            field=models.TextField(max_length=2000),
        ),
    ]
